# Generated by Django 4.2.4 on 2023-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_reserva_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
